name: CI
on:
  push:
    branches:
    - main
    paths:
    - '**.tex'
    - '**.sty'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Install tectonic
        uses: wtfjoke/setup-tectonic@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Compile all LaTeX documents
        run:  task filtr algebra
